# Generated by Django 2.2.7 on 2019-12-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workplace',
            name='unique_worker',
        ),
        migrations.AddConstraint(
            model_name='workplace',
            constraint=models.UniqueConstraint(fields=('worker', 'status'), name='unique_worker'),
        ),
    ]
