# Generated by Django 2.2.7 on 2019-11-26 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0002_auto_20191126_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='workplace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker', to='manage_app.Workplace'),
        ),
    ]
