# Generated by Django 2.2.7 on 2019-12-23 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0002_auto_20191212_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.EmailField(default='alina_selina@bk.ru', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='time_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('hours_worked', models.FloatField()),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='manage_app.Workplace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
