# Generated by Django 2.2.7 on 2020-01-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0004_auto_20191223_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name_plural': 'Statistics'},
        ),
    ]
